// This file is autogenerated. Changes will be overwritten.
#include <6IR33JEFVF/moc_DxvaVP9Decoder.cpp>
#include <6IR33JEFVF/moc_VP9Decoder.cpp>
#include <6IR33JEFVF/moc_VideoRenderer.cpp>
#include <6IR33JEFVF/moc_WebSocketReceiver.cpp>
#include <YPKJ5OE7LN/moc_BubbleTipWidget.cpp>
#include <YPKJ5OE7LN/moc_ScreenAnnotationWidget.cpp>
#include <C7JQLWOGWL/moc_AudioPlayer.cpp>
#include <C7JQLWOGWL/moc_VideoDisplayWidget.cpp>
