// This file is autogenerated. Changes will be overwritten.
#include <6NCFGKZLQE/moc_AnnotationOverlay.cpp>
#include <6NCFGKZLQE/moc_CursorOverlay.cpp>
#include <6NCFGKZLQE/moc_MouseCapture.cpp>
#include <6NCFGKZLQE/moc_PerformanceMonitor.cpp>
#include <6NCFGKZLQE/moc_ScreenCapture.cpp>
#include <6NCFGKZLQE/moc_VP9Encoder.cpp>
#include <6NCFGKZLQE/moc_WebSocketClient.cpp>
#include <6NCFGKZLQE/moc_WebSocketSender.cpp>
